### YamlMime:TSType
name: TestErrorChaosEvent
uid: '@azure/servicefabric.TestErrorChaosEvent'
package: '@azure/servicefabric'
summary: >-
  Describes a Chaos event that gets generated when an unexpected event occurs in
  the Chaos engine.

  For example, due to the cluster snapshot being inconsistent, while faulting an
  entity, Chaos

  found that the entity was already faulted -- which would be an unexpected
  event.
fullName: TestErrorChaosEvent
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: kind
    uid: '@azure/servicefabric.TestErrorChaosEvent.kind'
    package: '@azure/servicefabric'
    summary: Polymorphic Discriminator
    fullName: kind
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'kind: "TestError"'
      return:
        type: '"TestError"'
        description: ''
  - name: reason
    uid: '@azure/servicefabric.TestErrorChaosEvent.reason'
    package: '@azure/servicefabric'
    summary: >-
      Describes why TestErrorChaosEvent was generated. For example, Chaos tries
      to fault a partition

      but finds that the partition is no longer fault tolerant, then a
      TestErrorEvent gets generated

      with the reason stating that the partition is not fault tolerant.
    fullName: reason
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'reason?: undefined | string'
      return:
        type: undefined | string
        description: ''
  - name: timeStampUtc
    uid: '@azure/servicefabric.TestErrorChaosEvent.timeStampUtc'
    package: '@azure/servicefabric'
    summary: The UTC timestamp when this Chaos event was generated.
    fullName: timeStampUtc
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'timeStampUtc: Date'
      return:
        type: Date
        description: ''
